### ISSUE TITLE
Unexpected performance results

### ISSUE THREAD

**Issue by sinaahmadi** [amirveyseh/AAAI-21-SDU-shared-task-1-AI#3]
Using the provided `character_match.py` script, I created a baseline system and evaluated it with the `scorer` script. The performance of the baseline does not seem to be correctly evaluated with the latter script, as I am getting the following results on both `train` and `dev` predictions:

```
Shorts: P: 0.00%, R: 0.00%, F1: 0.00%
Longs: P: 0.00%, R: 0.00%, F1: 0.00%
micro scores: P: 0.00%, R: 0.00%, F1: 0.00%
macro scores: P: 0.00%, R: 0.00%, F1: 0.00%
Official Scores:
P: 0.00%, R: 0.00%, F1: 0.00%
```

Evaluating your provided `predictions.json` file also gives the following:

```
Shorts: P: 100.00%, R: 100.00%, F1: 100.00%
Longs: P: 100.00%, R: 100.00%, F1: 100.00%
micro scores: P: 100.00%, R: 100.00%, F1: 100.00%
macro scores: P: 100.00%, R: 100.00%, F1: 100.00%
Official Scores:
P: 100.00%, R: 100.00%, F1: 100.00%

```

In the description of the task, you report `Precision: 93.22%, Recall: 78.90%, F1: 85.46%`. Are those regarding the test sets? Is it normal that the baseline script results 0% or 100%?

**Comment by amirveyseh** [comment]
Thank you for reaching out. Please make sure that you run the scripts using
python 3, not Python 2. You can also check the predictions of your scripts
with the predictions made by the character_match.py script. If you run
character_match.py script in a python3 environment, you should be able to
get the reported performance.

Please note that the provided prediction.json file is just a reformatted
version of the dev.json file. So evaluating it on dev.json as the gold data
should give 100% precision and recall.

Please let me know if you have any other questions.

Thanks,
Amir

**Comment by sinaahmadi** [comment]
Thanks. Now it's a bit clearer but still, I am not sure why the baselines results are all 0%. To be clear, I use the baseline script on the dev and train datasets and evaluate the prediction results with `scorer` (not on your provided `predictions.json`).

**Comment by amirveyseh** [comment]
After cloning the repo, try to run the following lines of codes:

`python3 code/character_match.py -input dataset/dev.json -output output.json`

then 

`python3 scorer.py -g dataset/dev.json -p output.json`

Using this, you should be able to get the reported performance. If it doesn't work for you, please send me the output file of the `character_match.py` script.

**Comment by sinaahmadi** [comment]
Thanks. This was due to my Python version. Nothing wrong with your scripts.
