### ISSUE TITLE
Test data prediction file

### ISSUE THREAD

**Issue by sandaruSen** [amirveyseh/AAAI-21-SDU-shared-task-1-AI#5]
Hi, 
I was unable to locate the predictions file for the test data. Can I please get access to it?
Thanks

**Comment by sandaruSen** [comment]
I was able to locate them on huggingface.
Thanks.

**Comment by sandaruSen** [comment]
Hi,
The labels in the test set are all zeros on huggingface as well.
It would be great if you can share the test set prediction file.
Thank you

**Comment by QQingDDan** [comment]
Hi bro！Have you found the test set with ground truth labels?

**Comment by amirveyseh** [comment]
Test data with labels are added. Please check `dataset/truth.json`.
